"""Add payment_method to subscription purchases v.4

Revision ID: 040148ed09e6
Revises: 8059230f1c0e
Create Date: 2025-03-28 21:35:15.057643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '040148ed09e6'
down_revision = '8059230f1c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_vip_badge_elite', sa.Boolean(), nullable=True))
        batch_op.drop_column('gold')
        batch_op.drop_column('premuim')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premuim', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gold', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('has_vip_badge_elite')

    # ### end Alembic commands ###
