"""edit in table clup

Revision ID: 069a3021bf33
Revises: f878ce93b637
Create Date: 2025-03-22 13:05:00.543373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '069a3021bf33'
down_revision = 'f878ce93b637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_details', schema=None) as batch_op:
        batch_op.drop_column('center_back_1')
        batch_op.drop_column('center_forward')
        batch_op.drop_column('attacking_midfielder')
        batch_op.drop_column('left_back')
        batch_op.drop_column('defensive_midfielder')
        batch_op.drop_column('head_coach')
        batch_op.drop_column('right_back')
        batch_op.drop_column('central_midfielder')
        batch_op.drop_column('left_winger')
        batch_op.drop_column('center_back_2')
        batch_op.drop_column('right_winger')
        batch_op.drop_column('club_president')
        batch_op.drop_column('assistant_coach')
        batch_op.drop_column('goalkeeper')
        batch_op.drop_column('goalkeeper_coach')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goalkeeper_coach', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('goalkeeper', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('assistant_coach', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('club_president', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('right_winger', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('center_back_2', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('left_winger', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('central_midfielder', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('right_back', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('head_coach', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('defensive_midfielder', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('left_back', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('attacking_midfielder', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('center_forward', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('center_back_1', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
