"""0

Revision ID: 12a0814ab191
Revises: 678694fa9270
Create Date: 2025-05-01 06:14:07.637811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a0814ab191'
down_revision = '678694fa9270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription_purchases', schema=None) as batch_op:
        batch_op.drop_column('payment_link')

    # ### end Alembic commands ###
