"""add table promotion

Revision ID: 20b94485adcc
Revises: 5e6a102b474d
Create Date: 2025-03-27 19:10:43.218573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b94485adcc'
down_revision = '5e6a102b474d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('original_price', sa.Integer(), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), nullable=True),
    sa.Column('final_price', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('promotion_type', sa.String(length=50), nullable=True),
    sa.Column('coins_reward', sa.Integer(), nullable=True),
    sa.Column('free_packs', sa.Integer(), nullable=True),
    sa.Column('vip_duration_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.create_index('idx_promotions_active', ['is_active'], unique=False)
        batch_op.create_index('idx_promotions_type', ['promotion_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_index('idx_promotions_type')
        batch_op.drop_index('idx_promotions_active')

    op.drop_table('promotions')
    # ### end Alembic commands ###
