"""edit in table sub purch

Revision ID: 2584f69213ae
Revises: 040148ed09e6
Create Date: 2025-03-30 04:07:52.053262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2584f69213ae'
down_revision = '040148ed09e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_packs_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_pack_reset', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription_purchases', schema=None) as batch_op:
        batch_op.drop_column('last_pack_reset')
        batch_op.drop_column('daily_packs_used')

    # ### end Alembic commands ###
