"""add column can_manage_dashboard to users table

Revision ID: 29a1363c4ebb
Revises: e3edda0801cc
Create Date: 2025-03-28 02:35:15.826111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a1363c4ebb'
down_revision = 'e3edda0801cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_manage_dashboard', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_manage_dashboard')

    # ### end Alembic commands ###
