"""Add payment_method to subscription purchases v.3

Revision ID: 344052f6c1dc
Revises: c1b8e39fced9
Create Date: 2025-03-28 20:38:54.387486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344052f6c1dc'
down_revision = 'c1b8e39fced9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription_purchases', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
