"""add 2 coulm to user premuim and gold

Revision ID: 48204449251b
Revises: e6860f3e04f7
Create Date: 2025-03-12 22:53:08.124382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48204449251b'
down_revision = 'e6860f3e04f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premuim', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gold', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gold')
        batch_op.drop_column('premuim')

    # ### end Alembic commands ###
