"""add to user Add columns to track rewards

Revision ID: 5e6a102b474d
Revises: f6980a72ce3a
Create Date: 2025-03-26 19:31:46.786147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6a102b474d'
down_revision = 'f6980a72ce3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rare_expert_reward_collected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('catalog_king_reward_collected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('catalog_king_reward_collected')
        batch_op.drop_column('rare_expert_reward_collected')

    # ### end Alembic commands ###
