"""edit in table sub purch2

Revision ID: 641a1763f35f
Revises: 2584f69213ae
Create Date: 2025-03-30 04:13:59.319202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '641a1763f35f'
down_revision = '2584f69213ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription_purchases', schema=None) as batch_op:
        batch_op.drop_column('daily_packs_used')
        batch_op.drop_column('last_pack_reset')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_pack_reset', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('daily_packs_used', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
