"""Add is_subscribed to User table

Revision ID: 67da028ac4b8
Revises: 344052f6c1dc
Create Date: 2025-03-28 21:24:16.506066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67da028ac4b8'
down_revision = '344052f6c1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_subscribed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('is_subscribed')

    # ### end Alembic commands ###
