"""Add payment confirmation fields to UserSubscriptionPurchase

Revision ID: 69d428fdbd3e
Revises: a55fcbd61e5f
Create Date: 2025-04-29 23:03:53.323580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d428fdbd3e'
down_revision = 'a55fcbd61e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('paid_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription_purchases', schema=None) as batch_op:
        batch_op.drop_column('paid_amount')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
