"""Add image, phone, country, state, city to User

Revision ID: 8aae0a372a5f
Revises: 069a3021bf33
Create Date: 2025-03-23 09:07:23.522147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aae0a372a5f'
down_revision = '069a3021bf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('country')
        batch_op.drop_column('phone')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
