"""Remove foreign key constraint from Transaction model

Revision ID: 8db4aa47c539
Revises: 3f3ad31c40ef
Create Date: 2025-03-25 03:47:06.965876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8db4aa47c539'
down_revision = '3f3ad31c40ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('user_player_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint('transactions_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_foreign_key('transactions_ibfk_1', 'user_players', ['user_player_id'], ['id'])
        batch_op.alter_column('user_player_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
