"""edit in table subscription and user

Revision ID: a18b0c664e24
Revises: 29a1363c4ebb
Create Date: 2025-03-28 14:12:35.085658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18b0c664e24'
down_revision = '29a1363c4ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins_reward', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daily_free_packs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('joker_players', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_vip_badge', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_vip_badge_plus', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subscription_achievement_coins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allow_old_ahly_catalog', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_vip_badge', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_vip_badge_plus', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_vip_badge_plus')
        batch_op.drop_column('has_vip_badge')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('allow_old_ahly_catalog')
        batch_op.drop_column('subscription_achievement_coins')
        batch_op.drop_column('has_vip_badge_plus')
        batch_op.drop_column('has_vip_badge')
        batch_op.drop_column('joker_players')
        batch_op.drop_column('daily_free_packs')
        batch_op.drop_column('coins_reward')

    # ### end Alembic commands ###
