"""payment methods2

Revision ID: b54ffeb993b2
Revises: b3492c06f47e
Create Date: 2025-04-20 21:06:06.033868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54ffeb993b2'
down_revision = 'b3492c06f47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_config', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_column('gateway_config')

    # ### end Alembic commands ###
