"""Add payment_method to subscription purchases v.2

Revision ID: c1b8e39fced9
Revises: d3cc7f1ec6a6
Create Date: 2025-03-28 20:32:15.227301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b8e39fced9'
down_revision = 'd3cc7f1ec6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription_purchases', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
