"""Remove foreign key constraint from Transaction model2

Revision ID: ccea55a5de6a
Revises: 8db4aa47c539
Create Date: 2025-03-25 03:50:35.031423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccea55a5de6a'
down_revision = '8db4aa47c539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('transactions_ibfk_3', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_foreign_key('transactions_ibfk_3', 'users', ['seller_id'], ['id'])
        batch_op.create_foreign_key('transactions_ibfk_2', 'users', ['buyer_id'], ['id'])

    # ### end Alembic commands ###
