"""edit home

Revision ID: e2e6939c4751
Revises: 1f7706fee549
Create Date: 2025-04-29 17:44:37.293305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e6939c4751'
down_revision = '1f7706fee549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_egp', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('price_usd', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('price_usd')
        batch_op.drop_column('price_egp')

    # ### end Alembic commands ###
