"""Add page permissions to User model

Revision ID: e3edda0801cc
Revises: 20b94485adcc
Create Date: 2025-03-27 20:55:12.226298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3edda0801cc'
down_revision = '20b94485adcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_manage_users', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_players', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_clubs', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_packs', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_market', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_subscriptions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_promotions', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_manage_promotions')
        batch_op.drop_column('can_manage_subscriptions')
        batch_op.drop_column('can_manage_market')
        batch_op.drop_column('can_manage_packs')
        batch_op.drop_column('can_manage_clubs')
        batch_op.drop_column('can_manage_players')
        batch_op.drop_column('can_manage_users')

    # ### end Alembic commands ###
