"""add first_purchase_reward_collected field

Revision ID: e496ff61c228
Revises: 51ce8a5bb704
Create Date: 2025-03-24 15:53:56.356431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e496ff61c228'
down_revision = '51ce8a5bb704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_purchase_reward_collected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('first_purchase_reward_collected')

    # ### end Alembic commands ###
