"""add subscription_id column to users

Revision ID: e6860f3e04f7
Revises: 
Create Date: 2025-03-12 02:20:21.103259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6860f3e04f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_type', sa.String(length=100), nullable=False),
    sa.Column('package_details', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_outside_egypt', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('type_subscription', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('type_subscription')
        batch_op.drop_column('subscription')

    op.drop_table('subscriptions')
    # ### end Alembic commands ###
