"""add WalletRechargeRequest

Revision ID: f285a38eacb8
Revises: 12a0814ab191
Create Date: 2025-05-01 08:24:34.138647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f285a38eacb8'
down_revision = '12a0814ab191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_recharge_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_link', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('payment_proof', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['wallet_recharge_option.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('wallet_recharge_requests', schema=None) as batch_op:
        batch_op.create_index('idx_recharge_requests_status', ['status'], unique=False)
        batch_op.create_index('idx_recharge_requests_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_recharge_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_recharge_requests_user')
        batch_op.drop_index('idx_recharge_requests_status')

    op.drop_table('wallet_recharge_requests')
    # ### end Alembic commands ###
