"""add to user team_collector_reward_collected

Revision ID: f6980a72ce3a
Revises: ccea55a5de6a
Create Date: 2025-03-26 19:14:01.987400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6980a72ce3a'
down_revision = 'ccea55a5de6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_collector_reward_collected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('team_collector_reward_collected')

    # ### end Alembic commands ###
