"""Add payment gateway fields2

Revision ID: faefa9253df3
Revises: b54ffeb993b2
Create Date: 2025-04-21 01:55:50.399861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faefa9253df3'
down_revision = 'b54ffeb993b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gateway_api_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gateway_integration_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gateway_iframe_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_column('gateway_iframe_id')
        batch_op.drop_column('gateway_integration_id')
        batch_op.drop_column('gateway_api_key')
        batch_op.drop_column('gateway_type')

    # ### end Alembic commands ###
